<a href="https://colab.research.google.com/github/BBOMS9105/humanPython/blob/main/python230314.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 대분류

## 자기소개
- ㅁㅁㅁㅁ

In [ ]:
1+1

2

## 파이썬 기초 문법
- 주석처리
- 여러 줄 주석처리 시
  + 함수, 클래스 작성할 때
  요긴하게 쓰임 (예 : Docstring)
  

In [ ]:
# 이 코드는 주석처리

'''
여러줄 주석처리
123123
'''

"""
여러줄 
12414212
"""

print("Hello World")

Hello World


## 변수의 종류 (Scala 자료형)
- 크게 4가지 존재 : int, float, bool, None
- 더 이상 나누어지지 않는 것


### int 형 예제


In [ ]:
temp_int = 1
print(temp_int)
print(type(temp_int))

1
<class 'int'>


- 문자열

In [ ]:
temp_int = '1'
print(temp_int)
print(type(temp_int))

1
<class 'str'>


### float 형 예제
- 실수형

In [ ]:
num_float = 0.2
print(num_float)
print(type(num_float))

0.2
<class 'float'>


### Bool 형
- 참, 거짓

In [ ]:
temp_bool = True
temp_bool = False
print(temp_bool)
print(type(temp_bool))

False
<class 'bool'>


### None 자료형
- Null을 나타내는 자료형
  + 데이터분석에서 가장 처리하기 까다로운 자료형

In [ ]:
temp_none = None
print(type(temp_none))

<class 'NoneType'>


## 사칙연산
- 정수형 사칙연산 

In [ ]:
a = 7
b = 2
print(a + b)
print(a - b)
print(a * b)
print(a / b)  #나누면 실수형으로 결과를 출력한다 
print(a // b) #몫
print(a ** b) #제곱
print(a % b)  #나머지

9
5
14
3.5
3
49
1


### 실수형 사칙연산

In [ ]:
a = 7.0
b = 2.0
print(a + b)
print(a - b)
print(a * b)
print(a / b)  #나누면 실수형으로 결과를 출력한다 
print(a // b) #몫
print(a ** b) #제곱
print(a % b)  #나머지

9.0
5.0
14.0
3.5
3.0
49.0
1.0


### 논리형 연산자
- AND 조건, OR 조건이 있음

In [ ]:
print( True and True)
print( True and False)
print( False and True)
print( False and False)

True
False
False
False


In [ ]:
print( True or True)
print( True or False)
print( False or True)
print( False or False)

True
True
True
False


### 비교 연산자
- 비교 연산자는 부등호를 의미함
- 왼쪽이 기준 값

In [ ]:
print(4 > 3)
print(3 > 4)
print(3 >= 4)
print(3 <= 4)

True
False
False
True


## input()
- print() : 출력
- input() : 입력

In [ ]:
var = input("값을 입력해 주세요 : ")
var = int(var)
print(var)
print(type(var))

값을 입력해 주세요 : 3
3
<class 'int'>


In [ ]:
num1 = int(input("값을 입력해주세요"))
num2 = int(input("값을 입력해주세요"))

result = num1 + num2
print(result)
print(type(result))

값을 입력해주세요11
값을 입력해주세요89
100
<class 'int'>


## String 자료형
- 매우중요


### String 연산자

In [ ]:
str1 = "Hello "
str2 = "World"
print(str1 + str2)

Hello World


In [ ]:
str1 = "Hello "
str2 = "World"

result = str1 + str2
print(result)

Hello World


In [ ]:
str1 = "55"
str2 = "1122"
print(int(str1) + int(str2))

1177


- 곱셈 연산자 사용

In [ ]:
greeting = "Hello World  "
print(greeting * 3)

Hello World  Hello World  Hello World  


### Indexing
- 중요!
- 0번째부터 시작

In [ ]:
greeting = "Hello World!"
print(greeting[4])
print(greeting[-1])

o
!


### 슬라이싱
- 자름




In [ ]:
greeting = "Hello World"
print(greeting[0:5])
print(greeting[:])
print(greeting[6:])
print(greeting[3:8])
print(greeting[0:9:2])

Hello
Hello World
World
lo Wo
HloWr


In [ ]:
greeting = "Hello World"
greeting[13]

IndexError: ignored

### 문자열의 함수들
- 공식문서


## 문자열은 어떻게 만들고 사용할까?
- 1. 큰따옴표(")로 양쪽 둘러싸기

In [ ]:
"Hello World"

- 2. 작은따옴표(')로 양쪽 감싸기

In [ ]:
'Python is fun'

- 3. 큰따옴표 3개를 연속(""")으로 써서 양쪽 둘러싸기

In [ ]:
""" ABAABAB """

- 4. 작은따옴표 3개를 연속(''')으로 써서 양쪽 둘러싸기

In [ ]:
''' ABBABBA '''

### 문자열 안에 작은따옴표나 큰따옴표를 포함시키고 싶을 때
- 1. 문자열에 작은따옴표 (') 포함시키기


In [ ]:
food = "Python's favourite food is perl"
food

"Python's favourite food is perl"

- 2. 문자열에 큰따옴표 (") 포함시키기


In [ ]:
say = '"Python is very easy." he says.'

- 3. 백슬래시(\)를 사용해서 작은따옴표(')와 큰따옴표(")를 문자열에 포함시키기

In [ ]:
food = 'Python\'s favourite food is perl'
say = "\"Python is very easy.\" he says."

### 여러 줄인 문자열을 변수에 대입하고 싶을 때
- 1. 줄을 바꾸기 위한 이스케이프 코드 \n 삽입하기

In [ ]:
multiline = "life is too short／nYou need python"

'life is too short／nYou need python'

- 2. 연속된 작은따옴표 3개(''') 또는 큰따옴표 3개(""") 사용하기

In [ ]:
multiline='''
Life is too short
You need python
'''

In [ ]:
multiline="""
Life is too short
You need python
"""

### 문자열 연산하기
- 1. 문자열 더해서 연결하기(Connection)

In [ ]:
head = "Python"
tail = " is fun!"
head + tail

'Python is fun!'

- 2. 문자열 곱하기

In [ ]:
a = "python"
a * 2

'pythonpython'

- 3. 문자열 길이 구하기

In [ ]:
a = "Life is too short"
len(a)

17

## 문자열 인덱싱과 슬라이싱
- 1. 문자열 인덱싱 활용하기

In [ ]:
a = "Life is too short, You need Python"
a[0]
a[12]
a[-1]

'n'

- 2. 문자열에서 단어 뽑아내기

In [ ]:
a = "Life is too short, You need Python"
b = a[0] + a[1] + a[2] + a[3]
b

'Life'

- 3. 슬라이싱으로 문자열 나누기


In [ ]:
a = "20010331Rainy"
date = a[:8]
weather = a[8:]
print(date, weather)

20010331 Rainy


## 문자열 포매팅

- 1. 숫자 바로 대입

In [ ]:
"I eat %d apples." % 3

'I eat 3 apples.'

- 2. 문자열 바로 대입

In [ ]:
"I eat %s apples." % "five"

'I eat five apples.'

- 3. 2개 이상의 값 넣기


In [ ]:
number = 10
day = "three"
"I ate %d apples. so I was sick for %s days." % (number, day)

'I ate 10 apples. so I was sick for three days.'

4. 문자열 포맷 코드

- %s 문자열(String)
- %c 문자열 1개 (Character)
- %d 정수 (Interger)
- %f 부동소수 (floating-point)
- %o 8진수
- %x 16진수
- %% Literal%(문자 % 자체)

### format 함수를 사용한 포매팅
- 1. 숫자 바로 대입하기

In [ ]:
"I eat {0} apples.".format(3)

'I eat 3 apples.'

- 2. 문자열 바로 대입하기


In [ ]:
"I eat {0} apples.".format("five")

'I eat five apples.'

- 3. 숫자값을 가진 변수로 대입하기

In [ ]:
number = 3
"I eat {0} apples".format(number)

'I eat 3 apples'

- 4. 2개 이상의 값 넣기

In [ ]:
number = 3
day = "three"
"I eat {0} apples. So I was sick for {1} days".format(number,day)

'I eat 3 apples. So I was sick for three days'

- 5. 이름으로 넣기

In [ ]:
"I ate {number} apples. so I was sick for {day} days.".format(number=10, day=3)

'I ate 10 apples. so I was sick for 3 days.'

- 6. 인덱스와 이름을 혼용해서 넣기

In [ ]:
"I ate {0} apples. so I was sick for {day} days.".format(10, day=3)

'I ate 10 apples. so I was sick for 3 days.'

## 정렬
- 1. 왼쪽 정렬

In [ ]:
"{0:<10}".format("hi")

'hi        '

- 2. 오른쪽 정렬

In [ ]:
"{0:>10}".format("hi")

'        hi'

- 3. 가운데 정렬

In [ ]:
"{0:^10}".format("hi")

'    hi    '

- 4. 공백 채우기

In [ ]:
"{0:=^10}".format("hi")

'====hi===='

In [ ]:
"{0:!<10}".format("hi")

'hi!!!!!!!!'

- 5. 소수점 표현하기

In [ ]:
y = 3.42134234
"{0:0.4f}".format(y)

'3.4213'

6. { 또는 } 문자 표현하기

In [ ]:
"{{ and }}".format()

'{ and }'

- 7. f 문자열 포매팅

In [ ]:
name = '홍길동'
age = 30
f'나의 이름은 {name}입니다. 나이는 {age}입니다.'

'나의 이름은 홍길동입니다. 나이는 30입니다.'

f 문자열 포매팅은 위와 같이 name, age와 같은 변수 값을 생성한 후에 그 값을 참조할 수 있다. 또한 f 문자열 포매팅은 표현식을 지원하기 때문에 다음과 같은 것도 가능하다.

표현식이란 문자열 안에서 변수와 +, -와 같은 수식을 함께 사용하는 것을 말한다.

In [ ]:
age = 30
f'나는 내년이면 {age + 1}살이 된다.'

'나는 내년이면 31살이 된다.'

## 문자열 관련 함수들 (수업)
- 공식문서

In [ ]:
tmp_string = 'Java'

#변수명 저장과 동시에 클래스로 바뀜
print(tmp_string.upper())
print(tmp_string.lower())

JAVA
java


- 텍스트 분리

In [ ]:
tmp_string = 'BMW-BENZ-TESLA-KIA'

#변수명 저장과 동시에 클래스로 바뀜
print(tmp_string.split('-'))
#split(sep = '-')

['BMW', 'BENZ', 'TESLA', 'KIA']


참조 : [Python Docs](https://docs.python.org/3/library/stdtypes.html#str.split)

## 문자열 관련 함수들
- 1. 문자 개수 세기(count)

In [ ]:
a = "hobby"
a.count('b')

2

- 2. 위치 알려주기1 (find)

In [ ]:
a = "Python is the best choice"
a.find('b')

14

- 3. 위치 알려주기2(index)

In [ ]:
 a = "Life is too short"
a.index('t')
8

8

- 4. 문자열 삽입(join)

In [ ]:
",".join('abcd')

'a,b,c,d'

- 5. 소문자를 대문자로 바꾸기(upper)

In [ ]:
a = "hi"
a.upper()

'HI'

- 6. 대문자를 소문자로 바꾸기(lower)

In [ ]:
a = "HI"
a.lower()

'hi'

- 7. 왼쪽 공백 지우기(lstrip)

In [ ]:
a = " hi "
a.lstrip()

'hi '

- 8. 오른쪽 공백 지우기(rstrip)

In [ ]:
a= " hi "
a.rstrip()

' hi'

- 9. 양쪽 공백 지우기(strip)

In [ ]:
a = " hi "
a.strip()

'hi'

- 10. 문자열 바꾸기(replace)

In [ ]:
a = "Life is too short"
a.replace("Life", "Your leg")

'Your leg is too short'

- 11. 문자열 나누기(split)

In [ ]:
a = "Life is too short"
a.split()

['Life', 'is', 'too', 'short']

In [ ]:
b = "a:b:c:d"
b.split(':')

['a', 'b', 'c', 'd']

## 리스트
- 자바의 배열

In [ ]:
a = []
a_func = list() # list()함수로도 빈 리스트 생성 가능
b = [1]
c = ['Apple']
d = [1, 2, ['apple']]

print(a)
print(b)
print(c)
print(d)
print(a_func)

[]
[1]
['Apple']
[1, 2, ['apple']]
[]


In [ ]:
a = [5, 3, 1, 4, 6, 7]
print(a)

[5, 3, 1, 4, 6, 7]


In [ ]:
print(a[0:3])
print(a[1])

[5, 3, 1]
3


### 중첩리스트(Nested List)
- 리스트 내의 또 다른 리스트

In [ ]:
a = [['apple', 'banana', 'cherry'], 1]
a

[['apple', 'banana', 'cherry'], 1]

In [ ]:
# cherry 글자에서 알파벳 e만 가져오기
a[0][2][2]

'e'

In [ ]:
# cherry 글자에서 알파벳 e만 가져오기
temp = a[0]
temp2 = temp[2]
temp2[2]

'e'

### 리스트 연결 연산자
- 덧셈, 곱셈

In [ ]:
a = ['alice', 'bob', 'cat']
b = ['apple', 'banana', 'cherry']

c = a + b
print(c)

['alice', 'bob', 'cat', 'apple', 'banana', 'cherry']


In [ ]:
a = ['a', 'b', 'c']
b = a * 3
print(b)

['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'c']


In [ ]:
c = a * 0
print(c)

[]


### 리스트 값 수정


In [ ]:
a = [1,1,1]
a[1] = "b"

print(a)


[1, 'b', 1]


### 리스트 값 추가하기
- append 메소드 사용(기억)
- 반복문 사용 시 매우 자주 활용됨

In [ ]:
a = [100, 200, 300]
b = [400, 500, 600]
a.append(b)


print(a)

[100, 200, 300, [400, 500, 600]]


### extend( ) 함수 사용
- 여러 개의 요소를 추가하고 싶을 때 사용

In [ ]:
a = [100, 200, 300]
b = [400, 500, 600]

a.extend(b)

print(a)

[100, 200, 300, 400, 500, 600]


### insert( )
- 특정한 위치에 값을 추가

In [ ]:
a = [1, 1, 1, 1, 1, 1, 1]
a.insert(2, 100)

print(a)

[1, 1, 100, 1, 1, 1, 1, 1]


### 리스트의 값을 삭제
- remove() 함수

In [ ]:
a = [5, 4, 3, 2, 1]
a.remove(4) # 숫자는 인덱스 번호가 아님
a

[5, 3, 2, 1]

- pop 함수 

In [ ]:
a = [5, 4, 3, 2, 1]
a2 = a.pop(4) # a2 에 제거한 값이 저장됨
print(a2, a)

1 [5, 4, 3, 2]


## 그 외 유용한 메소드
- clear 함수

In [ ]:
a = [0,1,2,3]
print(a)

a.clear()
print(a)

[0, 1, 2, 3]
[]


In [ ]:
a = [1, 4, 5, 2, 3]
a.sort()
print(a)

[1, 2, 3, 4, 5]


In [ ]:
# a 를 내림차순으로 정렬하기
# a.sort() a.sort(reverse=False) : 오름차순 정렬
# a.sort(reverse=True) : 내림차순 정렬
a.sort(reverse=True)
a

[5, 4, 3, 2, 1]

## 튜플


In [ ]:
tuple01 = (0)
tuple02 = (0, )
tuple03 = 0, 1, 2

print(tuple01)
print(tuple02)
print(tuple03)

print(type(tuple01))
print(type(tuple02))
print(type(tuple03))

0
(0,)
(0, 1, 2)
<class 'int'>
<class 'tuple'>
<class 'tuple'>


In [ ]:
# packing
my_tuple = 3, 2, "A"
print(my_tuple)

# Unpacking
a, b, c = my_tuple

print(a)
print(b)
print(c)

(3, 2, 'A')
3
2
A


### 수정, 삭제 불가능

In [ ]:
# List
a = [0, 1, 2, 3, 4, 5, "a"]
del a[6]
a

[0, 1, 2, 3, 4, 5]

In [ ]:
a = (0, 1, 2, 3, 4, 5, "a")
print(a[6])
# del a[6]

a


In [ ]:
# Tuple
a = (0, 1, 2, 3, 4, 5, "a")
#print(a[6])
del a[6]

TypeError: ignored

- 수정

In [ ]:
# List
a = [1, 1, 1, 'a']
a[3] = 1
a

[1, 1, 1, 1]

In [ ]:
#Tuple
a = (1, 1, 1, 'a')
a[3] = 1
a

TypeError: ignored

### 슬라이싱, 인덱싱
- 각자 실습

### 더하기 및 곱셈 연산자 사용

In [ ]:
t1 = (0, 1, 2, 3, 4)
t2 = ('a', 'b', 'c')

print(t1 + t2)
print(t1 * 3)
print(t1 * 0)

(0, 1, 2, 3, 4, 'a', 'b', 'c')
(0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4)
()


## Dictionary


In [ ]:
temp_dict = {
    "a" : [0, 1, 2, 3],
    "b" : "휴먼",
    "c" : 100
}

temp_dict

{'a': [0, 1, 2, 3], 'b': '휴먼', 'c': 100}

In [ ]:
temp_dict['c']

100

In [ ]:
temp_dict['d']
# KeyError

KeyError: ignored

In [ ]:
temp_dict.keys()
# Key 만 출력

dict_keys(['a', 'b', 'c'])

In [ ]:
print(type(temp_dict.keys()))

# 리스트로 변환
result = list(temp_dict.keys())
print(result)
print(type(result))

<class 'dict_keys'>
['a', 'b', 'c']
<class 'list'>


In [ ]:
result = temp_dict.values()
print(type(result))
print(result) # Value 출력

<class 'dict_values'>
dict_values([[0, 1, 2, 3], '휴먼', 100])


In [ ]:
a = {
    'name' : '휴먼',
    'age' : 50,
    'job' : '학생'
}
result = list(a.items())
result


[('name', '휴먼'), ('age', 50), ('job', '학생')]

## if 문

In [ ]:
a = 6

if a > 5:
  print("a가 5보다 크다")
elif a > 0:
  print("a가 0보다 크다")
else:
  print("음수")

a가 5보다 크다


In [ ]:
# input 함수
# 90점 이상 A등급, 80점 이상 B등급 나머지 C등급
score = int(input("점수를 입력하세요 : "))

if score >= 90:
  print("A 등급")
elif score >= 80:
  print("B 등급")
else:
  print("C 등급")

점수를 입력하세요 : 30
C 등급


## 반복문
- 반복문은 왜 쓰는가?
> 시간 아끼려고

In [ ]:
# 과제 Hello World 3 번 출력
for i in range(3):
  # range 자리에는 다향한 개체들이 온다
  print("Hello World")

Hello World
Hello World
Hello World


In [ ]:
letters = ['A', 'B', 'C']
for idx, value in enumerate(letters):
  print(idx, value)

0 A
1 B
2 C


In [ ]:
fruits = ['apple', 'kiwi', 'mango']
# 리스트의 값 중에서 a가 들어간 단어만 출력
# list comprehesion
newlists = [fruit for fruit in fruits if "a" in fruit]
print(newlists)

['apple', 'mango']


In [ ]:
fruits = ['apple', 'kiwi', 'mango']

newlist = []
for fruit in fruits:
  #1단계
  print(fruit)

  # 2단계 : 조건문을 작성할 수 있다.
  # True False 식을 도출
  if "a" in fruit:
    newlist.append(fruit)

print(newlist)

apple
kiwi
mango
['apple', 'mango']


# 파이썬 라이브러리

## NumPy

### NumPy 라이브러리 불러오기


In [ ]:
import numpy as np # numpy 라이브러리를 약어 np로 불러오기
print(np.__version__)

1.22.4


### 리스트를 배열로 변환

In [ ]:
temp = [1, 2, 3, 4, 5, 6, 7, 8 ,9, 10]
temp_array = np.array(temp)
print(temp)
print(temp_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(type(temp))
print(type(temp_array))
print(temp_array.shape)
print(temp_array.ndim)

<class 'list'>
<class 'numpy.ndarray'>
(10,)
1


- n 번째 인수를 출력

In [ ]:
temp_array[1]

2

In [ ]:
temp_array[-1]

10

### 사칙연산

In [ ]:
score1 = [10, 15, 40, 25, 13, 33]
score2 = [30, 40, 12, 124, 123, 222]

score1 + score2

[10, 15, 40, 25, 13, 33, 30, 40, 12, 124, 123, 222]

In [ ]:
score1_arr = np.array(score1)
score2_arr = np.array(score2)

result = score1_arr + score2_arr

In [ ]:
result

array([ 40,  55,  52, 149, 136, 255])

In [ ]:
# 최솟값
np.min(result)

40

In [ ]:
# 최댓값
np.max(result)

255

In [ ]:
#SUM
np.sum(result)

687

### 배열(행렬,Matrix)의 생성
- 0차원부터 3차원까지로 구성

In [ ]:
temp_arr = np.array(30)
print(temp_arr)
print(type(temp_arr))
print(temp_arr.shape)

30
<class 'numpy.ndarray'>
()


In [ ]:
# .shape / .ndim
temp_arr = np.array([1, 2, 3])
print(temp_arr.shape) # 행렬의 형태
print(temp_arr.ndim) # n차원

(3,)
1


### 2차원 배열
- 정형 데이터(엑셀 데이터)

In [ ]:
# 2차원 배열 생성
temp_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(temp_arr.shape) # 행렬의 형태
print(temp_arr.ndim) # n차원

(2, 3)
2


### 3차원 배열
- 이미지 데이터

In [ ]:
# 3차원 배열 생성
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(temp_arr.shape) # 행렬의 형태
print(temp_arr.ndim) # n차원

(2, 2, 3)
3


In [ ]:
#ndmin 배열을 n차원으로 보이게 만든다
temp_arr = np.array([1, 2, 3, 4], ndmin = 2)
print(temp_arr.shape)
print(temp_arr.ndim)

(1, 4)
2


### 배열을 생성하는 다양한 방법들
- 모두 0으로 채우기


In [ ]:
temp_arr = np.zeros((10, 5))
temp_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- 1로 채우기

In [ ]:
temp_arr = np.ones((10, 5))
temp_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- 임의의 상수값으로 채우기

In [ ]:
temp_arr = np.full((2,3), 10)
temp_arr

array([[10, 10, 10],
       [10, 10, 10]])

- 최소 및 최대 숫자의 범위를 정하고, 구간 별로 값 생성하기

In [ ]:
# np.linspace(최솟값, 최댓값, 값의 갯수)
temp_arr = np.linspace(5, 10, 9)
temp_arr

array([ 5.   ,  5.625,  6.25 ,  6.875,  7.5  ,  8.125,  8.75 ,  9.375,
       10.   ])

- np.arange()

In [ ]:
temp_arr = np.arange(1, 100, 4)
temp_arr

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

- 임의의 난수 생성

In [ ]:
from numpy import random
x = random.rand()
print(x)

0.5398128065430364


### 배열 연산
- 덧셈 : np.add()
- 뺄셈 : np.subtract()
- 곱셈 : np.multiply()
- 나눗셈 : np.divide()

In [ ]:
import numpy as np

array_01 = np.array([1, 2, 3])
array_02 = np.array([10, 20, 30])

result = np.add(array_01, array_02)
result

array([11, 22, 33])

In [ ]:
# 뺄셈
result = np.subtract(array_01, array_02)
result

array([ -9, -18, -27])

In [ ]:
# 곱셈
result = np.multiply(array_01, array_02)
result

array([10, 40, 90])

In [ ]:
# 나눗셈
result = np.divide(array_01, array_02)
result

array([0.1, 0.1, 0.1])

In [ ]:
array_01 = np.array([1, 2, 3])
array_02 = np.array([1, 2, 3])
# 거듭제곱
result = np.power(array_01, array_02)
result

array([ 1,  4, 27])

### 소숫점 정렬

- 코드는 실행속도가 빨라야 한다

In [ ]:
# 소숫점 날리기

temp_arr = np.trunc([-1.23, 1.23])
print(temp_arr)

[-1.  1.]


In [ ]:
# 소숫점 날리기

temp_arr = np.fix([-1.23, 1.23])
print(temp_arr)

[-1.  1.]


- 소숫점 n번째 자리에서 반올림

In [ ]:
temp_arr = np.around([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

In [ ]:
temp_arr = np.round([-1.123131, 1.123131], 3)
temp_arr

array([-1.123,  1.123])

- 소숫점 모두 내리기

In [ ]:
temp_arr = np.floor([-1.23456, 1.23456])
print(temp_arr)

[-2.  1.]


- 올림

In [ ]:
temp_arr = np.ceil([-1.23456, 1.23456])
print(temp_arr)

[-1.  2.]


### 조건문
- where : 조건식 1개일 때 활용
- select : 다중 조건일 때 활용

In [ ]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- np.where()

In [ ]:
np.where(temp_arr < 5, temp_arr, 10 * temp_arr)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

np.select()

In [ ]:
temp_arr = np.arange(10)
cond_list = [temp_arr > 5, temp_arr < 2]
choice_list = [temp_arr * 3, temp_arr + 10]
np.select(cond_list, choice_list, default = temp_arr)

array([10, 11,  2,  3,  4,  5, 18, 21, 24, 27])